# Generated by Django 4.0.2 on 2022-02-22 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stamp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateTimeField(auto_now=True)),
                ('break_start', models.DateTimeField()),
                ('break_end', models.DateTimeField()),
                ('end', models.DateTimeField()),
            ],
        ),
    ]
