# Generated by Django 4.0.2 on 2022-02-27 05:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
        ('stamp', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stamp',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='company.company'),
        ),
    ]
