# Generated by Django 4.0.2 on 2022-02-27 05:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stamp', '0003_stamp_company'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stamp',
            options={'ordering': ['-id']},
        ),
    ]
