# Generated by Django 4.0.2 on 2022-02-27 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stamp', '0005_alter_stamp_start'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stamp',
            name='break_end',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='stamp',
            name='break_start',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
