# Generated by Django 4.0.2 on 2022-02-27 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_profile_break_end_profile_break_start_profile_end_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='mode',
            field=models.IntegerField(default=0),
        ),
    ]
