# Generated by Django 4.0.2 on 2022-02-27 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_profile_mode'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='mode',
            new_name='state',
        ),
    ]
